title: Hana Matsumoto

#remote_theme: "Scriptor-Jekyll-Theme"
#theme: jekyll-theme-minimal
theme: minima

header_pages:
  - index.md
  - about.md
  - projects.md

collections:
  projects:
    output: true   # each project gets its own page

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
