title: Hana Matsumoto

#remote_theme: "Scriptor-Jekyll-Theme"
#theme: jekyll-theme-minimal
theme: minima
css: "/assets/css/style.css"

header_pages:
  - index.md
  - projects.md
  - resume.md

collections:
  projects:
    output: true   # each project gets its own page

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
